version: '2'

volumes:
  jenkins_data: {}

services:
  jenkins:
    restart: always
    image: jenkins:1.651.3
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=jenkins.spistresci.pl
      - VIRTUAL_PORT=8080
    network_mode: 'bridge'

